version: "3.8"

services:
  standup:
    build: .
    container_name: standup-app
    ports:
      - "9060:9060"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
